server:
  port: 8761
spring:
  cloud:
    config:
      uri: http://localhost:8765/
      profile: test
      label: test
eureka:
   instance:
       hostname: localhost
   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/