server:
  port: 8761
spring:
  cloud:
    config:
      profile: prod
      label: prod
      discovery:
        enabled: true
        serviceId: config-server
eureka:
   instance:
       hostname: localhost
   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/