server:
  port: 8761
spring:
  application:
    name: eureka-server
  cloud:
    config:
      profile: ${spring.profiles.active}
      label: ${spring.application.name}
      discovery:
        enabled: true
        serviceId: config-server
eureka:
   instance:
       hostname: localhost
   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/