eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8768
spring:
    application:
        name: api-sso-server
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        pool:
            max-active: 100
            max-idle: 10
            max-wait: 100000
        timeout: 0
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/wust?useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
    cloud:
        config:
            profile: ${spring.profiles.active}
            label: test
            discovery:
                enabled: true
                serviceId: config-server
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        mapUnderscoreToCamelCase: true
mapper:
    mappers: com.wust.springcloud.common.dao.IBaseMapper
    identity: MYSQL