eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: api-config-server
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
    timeout: 0
  cloud:
    config:
      server:
        git:
          uri: https://github.com/roncoo-eshop/roncoo-eshop-config
          searchPaths: config-file
          username: wusongti@163.com
          password: songti.wu123
      label: master
