eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: api-config-server
  profiles:
    active: master
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
    timeout: 0
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wusongti/config.git
          default-label: ${spring.profiles.active}   #解决监控down
          searchPaths: /
          username: wusongti@163.com
          password:
