exchange:
  exportexcel:
    name: ${mq.env}.exportexcel.exchange
queue:
  exportexcel:
    name: ${mq.env}.exportexcel.queue
routing:
  exportexcel:
    key:
      name: ${mq.env}.exportexcel.routing.key