exchange:
  exportexcel:
    name: ${mq.env}.exportexcel.exchange
  importexcel:
    name: ${mq.env}.importexcel.exchange
queue:
  exportexcel:
    name: ${mq.env}.exportexcel.queue
  importexcel:
    name: ${mq.env}.importexcel.queue
routing:
  exportexcel:
    key:
      name: ${mq.env}.exportexcel.routing.key
  importexcel:
    key:
      name: ${mq.env}.importexcel.routing.key